'use strict';
const GAME_ID='battle-line', GAME_NAME='バトルライン', MAX_PLAYERS=2, APP_VERSION='v0.1';
const WORKER_ORIGIN=String(window.BATTLE_LINE_WORKER_ORIGIN||'').replace(/\/$/,'');
const COMMON_PLAYER_NAME_KEY='boardgamePlayerName', ROOM_IDS=['room1','room2','room3','room4'];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let ws=null,currentRoomId=null,currentPlayerName='',state=null,selectedCard=null,reconnectTimer=null,commonNameSavedForSession=null,actionSeq=0;
function commonSavedName(){return String(localStorage.getItem(COMMON_PLAYER_NAME_KEY)||'').trim().slice(0,32)}
function saveCommonNameOnActualStart(n){n=String(n||'').trim().slice(0,32);if(n)localStorage.setItem(COMMON_PLAYER_NAME_KEY,n)}
function tokenKey(r){return `${GAME_ID}-online-token-${r}`}; function getToken(r){let t=localStorage.getItem(tokenKey(r));if(!t){t=crypto.randomUUID().replace(/-/g,'');localStorage.setItem(tokenKey(r),t)}return t}
function newActionId(p='op'){actionSeq=(actionSeq+1)%1e6;return[p,Date.now(),actionSeq,Math.random().toString(36).slice(2,8)].join('-')}
function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function screen(id){$$('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active')}
function api(path,opt){if(WORKER_ORIGIN.includes('CHANGE-ME'))return Promise.reject(new Error('config.js にWorker URLを設定してください'));return fetch(WORKER_ORIGIN+path,opt)}
async function loadRooms(){try{const r=await api('/rooms',{cache:'no-store'}),d=await r.json();renderRooms(d.rooms||[])}catch(e){renderRooms([]);toast(e.message)}}
function renderRooms(rooms){$('#rooms').innerHTML=ROOM_IDS.map((id,i)=>{const r=rooms.find(x=>x.roomId===id)||{players:[],status:'lobby'};const names=(r.players||[]).map(x=>x.name).join(' / ')||'なし';return `<article class="room"><h2>ROOM ${i+1}</h2><div class="status">${r.status==='playing'?'ゲーム中':r.status==='finished'?'終了':'待機中'}</div><b>${(r.players||[]).length} / 2人</b><div class="players">参加者：${esc(names)}</div><button class="join" data-room="${id}">${r.reconnectable?'再接続':'参加する'}</button><button class="reset" data-reset="${id}">初期化</button></article>`}).join('');$$('[data-room]').forEach(b=>b.onclick=()=>joinRoom(b.dataset.room));$$('[data-reset]').forEach(b=>b.onclick=()=>resetRoom(b.dataset.reset))}
async function resetRoom(id){if(!confirm(`ROOM ${ROOM_IDS.indexOf(id)+1} を初期化しますか？`))return;try{const r=await api(`/reset-empty?roomId=${id}`,{method:'POST'}),d=await r.json();if(!r.ok)throw Error(d.error||'初期化できません');loadRooms()}catch(e){toast(e.message)}}
async function joinRoom(id){const name=$('#name').value.trim().slice(0,32);if(!name)return toast('プレイヤー名を入力してください');const token=getToken(id);try{const r=await api(`/join-check?roomId=${id}&name=${encodeURIComponent(name)}&token=${token}`,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'ROOMへ参加できません');currentRoomId=id;currentPlayerName=name;localStorage.setItem(`${GAME_ID}-online-room`,id);localStorage.setItem(`${GAME_ID}-online-active-name`,name);connect()}catch(e){toast(e.message)}}
function connect(){if(ws)try{ws.close()}catch{};const u=new URL(WORKER_ORIGIN);u.protocol=u.protocol==='https:'?'wss:':'ws:';u.pathname='/ws';u.searchParams.set('roomId',currentRoomId);u.searchParams.set('name',currentPlayerName);u.searchParams.set('token',getToken(currentRoomId));ws=new WebSocket(u);ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='state'){state=m.state;onState()}else if(m.type==='error')toast(m.error)};ws.onclose=()=>{if(currentRoomId)scheduleReconnect()};ws.onerror=()=>{} }
function scheduleReconnect(){clearTimeout(reconnectTimer);reconnectTimer=setTimeout(()=>{if(currentRoomId&&(!ws||ws.readyState!==1))connect()},1800)}
function send(type,data={}){if(!ws||ws.readyState!==1)return toast('再接続中です');ws.send(JSON.stringify({type,actionId:newActionId(type),...data}))}
function onState(){if(state.status==='playing'&&state.gameSessionId&&commonNameSavedForSession!==state.gameSessionId){saveCommonNameOnActualStart(currentPlayerName);commonNameSavedForSession=state.gameSessionId}if(state.status==='lobby')renderLobby();else renderGame();}
function me(){return state?.players?.find(p=>p.token===getToken(currentRoomId))} function opp(){const m=me();return state?.players?.find(p=>p.id!==m?.id)}
function renderLobby(){screen('#lobby');$('#lobbyRoom').textContent=`ROOM ${ROOM_IDS.indexOf(currentRoomId)+1}`;$('#seats').innerHTML=(state.players||[]).map((p,i)=>`<p><b>${i+1}.</b> ${esc(p.name)} ${p.cpu?'（CPU Lv'+p.cpu+'）':''}${p.id===state.hostId?' ★HOST':''}</p>`).join('')||'<p>待機中</p>';const host=me()?.id===state.hostId;$('#hostSettings').style.opacity=host?'1':'.55';$('#startBtn').style.display=host?'block':'none';for(const [id,key] of [['tactics','tactics'],['claimRule','claimRule'],['first','first'],['cpu','cpuLevel']]){$('#'+id).value=String(state.settings?.[key]??(id==='tactics'?'true':id==='claimRule'?'normal':id==='first'?'random':'0'));$('#'+id).disabled=!host} }
function cardHtml(c,hand=false){if(!c)return '<div class="slot"></div>';if(c.kind==='troop')return `<div class="card ${c.color}" data-card="${c.id}"><span>${colorMark(c.color)}</span><b>${c.value}</b></div>`;return `<div class="card tactic" data-card="${c.id}" title="${esc(c.text||'')}"><small>戦術</small><b>${esc(c.name)}</b></div>`}
function colorMark(c){return ({red:'赤',blue:'青',green:'緑',yellow:'黄',purple:'紫',orange:'橙'})[c]||c}
function renderGame(){screen('#game');const m=me(),o=opp();if(!m)return;$('#oppInfo').innerHTML=`<b>${esc(o?.name||'CPU')}</b>　手札 ${o?.handCount??0}　⚑${o?.flags??0}`;$('#myInfo').innerHTML=`<b>${esc(m.name)}</b>　⚑${m.flags||0}　使用戦術 ${m.tacticsUsed||0}`;$('#phaseText').textContent=phaseLabel();$('#troopDeck b').textContent=state.troopDeckCount;$('#tacticDeck b').textContent=state.tacticDeckCount;$('#tacticDeck').style.display=state.settings.tactics?'block':'none';const myTurn=state.turnPlayerId===m.id;$('#troopDeck').classList.toggle('ready',myTurn&&state.phase==='draw');$('#tacticDeck').classList.toggle('ready',myTurn&&state.phase==='draw');renderBattle();$('#hand').innerHTML=(m.hand||[]).map(cardHtml).join('');$$('#hand .card').forEach(el=>{el.onclick=()=>selectCard(el.dataset.card);if(el.dataset.card===selectedCard)el.classList.add('selected')});if(state.status==='finished')showResult()}
function phaseLabel(){const m=me(),turn=state.turnPlayerId===m?.id?'あなた':'相手';if(state.status==='finished')return 'ゲーム終了';return `${turn}の手番 / ${state.phase==='play'?'カード配置':state.phase==='draw'?'カードを引く':'処理中'}`}
function renderBattle(){const m=me();$('#battlefield').innerHTML=state.flags.map((f,i)=>{const mine=f.sides[m.seat]||[],other=f.sides[1-m.seat]||[];const top=m.seat===0?other:mine,bottom=m.seat===0?mine:other;const owner=f.ownerId===m.id?'mine':f.ownerId?'opp':'';return `<div class="lane" data-lane="${i}"><div class="formation">${top.map(cardHtml).join('')}${slots(f,top.length)}</div><div class="flag ${owner} ${f.claimableByMe?'claimable':''}" data-claim="${i}">⚑ ${i+1}<small>${f.effect?'<br>'+esc(f.effect):''}</small><span class="role">${esc(f.summary||'')}</span></div><div class="formation">${bottom.map(cardHtml).join('')}${slots(f,bottom.length)}</div></div>`}).join('');$('#flagNav').innerHTML=state.flags.map((f,i)=>`<button class="${f.ownerId===m.id?'mine':f.ownerId?'opp':''}" data-nav="${i}">${i+1}</button>`).join('');$$('[data-nav]').forEach(b=>b.onclick=()=>$$('.lane')[+b.dataset.nav].scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'}));$$('.lane').forEach(l=>l.onclick=e=>{if(e.target.closest('.flag.claimable'))return; if(selectedCard)playSelected(+l.dataset.lane)});$$('.flag.claimable').forEach(f=>f.onclick=e=>{e.stopPropagation();send('claim',{flag:+f.dataset.claim})})}
function slots(f,n){const max=f.mud?4:3;return Array.from({length:Math.max(0,max-n)},()=>'<div class="slot"></div>').join('')}
function selectCard(id){if(state.turnPlayerId!==me()?.id||state.phase!=='play')return toast('今はカードを出せません');selectedCard=selectedCard===id?null:id;renderGame()}
function playSelected(flag){const c=me().hand.find(x=>x.id===selectedCard);if(!c)return;if(c.kind==='tactic'&&['deserter','redeploy','traitor'].includes(c.code)){openTacticTarget(c,flag);return}send('play',{cardId:selectedCard,flag});selectedCard=null}
function openTacticTarget(c,flag){const choices=[];state.flags.forEach((f,fi)=>f.sides.forEach((arr,seat)=>arr.forEach(x=>choices.push({fi,seat,x}))));let html=`<h2>${esc(c.name)}</h2><p>${esc(c.text)}</p>`;if(c.code==='deserter')html+=choices.filter(q=>q.seat!==me().seat&&!state.flags[q.fi].ownerId).map(q=>`<button class="targetCard" data-fi="${q.fi}" data-id="${q.x.id}">旗${q.fi+1} ${esc(cardLabel(q.x))}</button>`).join('');if(c.code==='redeploy')html+=choices.filter(q=>q.seat===me().seat&&!state.flags[q.fi].ownerId).map(q=>`<button class="targetCard" data-fi="${q.fi}" data-id="${q.x.id}">旗${q.fi+1} ${esc(cardLabel(q.x))}</button>`).join('');if(c.code==='traitor')html+=choices.filter(q=>q.seat!==me().seat&&q.x.kind==='troop'&&!state.flags[q.fi].ownerId).map(q=>`<button class="targetCard" data-fi="${q.fi}" data-id="${q.x.id}">旗${q.fi+1} ${esc(cardLabel(q.x))}</button>`).join('');modal(html);$$('.targetCard').forEach(b=>b.onclick=()=>{closeModal();send('play',{cardId:c.id,flag,targetFlag:flag,sourceFlag:+b.dataset.fi,targetCardId:b.dataset.id});selectedCard=null})}
function cardLabel(c){return c.kind==='troop'?`${colorMark(c.color)}${c.value}`:c.name}
function modal(h){$('#modalBody').innerHTML=h;$('#modal').classList.remove('hidden')} function closeModal(){$('#modal').classList.add('hidden')}
function showResult(){if(!$('#modal').classList.contains('hidden'))return;const win=state.winnerId===me()?.id;modal(`<div class="result"><h2>${win?'WIN':'LOSE'}</h2><p>${esc(state.winReason||'')}</p><p>${esc(me().name)}：⚑${me().flags}　${esc(opp()?.name||'CPU')}：⚑${opp()?.flags||0}</p><button id="boardBtn">盤面を見る</button> <button id="lobbyBtn">ロビーへ</button> <button id="rematchBtn">再戦</button></div>`);$('#boardBtn').onclick=closeModal;$('#lobbyBtn').onclick=()=>send('backLobby');$('#rematchBtn').onclick=()=>send('rematch')}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c])}
$('#name').value=sessionStorage.getItem('battle-line-name-draft')??commonSavedName();$('#name').oninput=e=>sessionStorage.setItem('battle-line-name-draft',e.target.value);
$('#leaveBtn').onclick=leaveCurrentRoom;$('#startBtn').onclick=()=>send('start');
for(const [id,key] of [['tactics','tactics'],['claimRule','claimRule'],['first','first'],['cpu','cpuLevel']])$('#'+id).onchange=e=>send('settings',{key,value:id==='tactics'?e.target.value==='true':id==='cpu'?+e.target.value:e.target.value});
$('#troopDeck').onclick=()=>{if(state?.phase==='draw')send('draw',{deck:'troop'})};$('#tacticDeck').onclick=()=>{if(state?.phase==='draw')send('draw',{deck:'tactic'})};$('#historyBtn').onclick=()=>modal('<h2>ログ</h2>'+(state.history||[]).slice().reverse().map(x=>`<div class="log">${esc(x)}</div>`).join(''));
$('#rulesBtn').onclick=()=>modal(`<div class="rules"><h2>ルール・用語</h2><h3>勝利条件</h3><p>中央の9本のフラッグを争います。<b>隣接する3本を連続で獲得</b>するか、場所を問わず<b>5本を獲得</b>すると勝利です。</p><h3>ターン</h3><p>基本は「カードを1枚プレイ → 部隊山札または戦術山札から1枚ドロー → 相手の手番」です。フラッグは獲得可能になった時に旗を押して宣言します。</p><h3>フォーメーション</h3><table><tr><th>強さ</th><th>名称</th><th>意味</th></tr><tr><td>1</td><td class="term">ウェッジ</td><td>同じ色で連続した数字</td></tr><tr><td>2</td><td class="term">ファランクス</td><td>同じ数字</td></tr><tr><td>3</td><td class="term">バタリオン</td><td>同じ色</td></tr><tr><td>4</td><td class="term">スカーミッシャー</td><td>連続した数字</td></tr><tr><td>5</td><td class="term">ホスト</td><td>上記以外</td></tr></table><p>同じフォーメーションなら数字合計が大きい側が上です。同種・同合計なら先に完成した側が上です。</p><h3>フラッグ獲得</h3><p>相手が未完成でも、公開済みカードから見て相手が残りをどう完成させてもこちらを上回れない場合は獲得宣言できます。手札の中身は判定材料にしません。</p><h3>戦術カード</h3><p><span class="term">リーダー</span>：色・数字を自由に扱うワイルド。　<span class="term">援軍騎兵</span>：数字8で色自由。　<span class="term">盾兵</span>：数字1～3で色自由。</p><p><span class="term">霧</span>：その旗は役を無視して合計値で比較。　<span class="term">泥濘</span>：その旗を4枚編成に変更。</p><p><span class="term">偵察</span>：カードを追加で確認・交換する戦術。　<span class="term">再配置</span>：自分の配置済みカードを移動。　<span class="term">脱走</span>：相手の配置済みカードを捨てる。　<span class="term">裏切り</span>：相手の部隊カードを自分側へ移す。</p><h3>戦術カードの枚数制限</h3><p>自分が使える戦術カード枚数は、常に相手の使用枚数より最大1枚多いところまでです。</p><h3>用語</h3><p><span class="term">部隊カード</span>：6色×1～10の通常カード。　<span class="term">戦線</span>：各フラッグを挟んだ双方のカード配置場所。　<span class="term">獲得宣言</span>：条件を満たしたフラッグを自分のものとして確定する操作。</p></div>`);
function leaveCurrentRoom(){if(!currentRoomId)return; if(!confirm('ROOMから退室しますか？'))return; send('leave'); const room=currentRoomId; currentRoomId=null; state=null; selectedCard=null; clearTimeout(reconnectTimer); localStorage.removeItem(`${GAME_ID}-online-room`);localStorage.removeItem(`${GAME_ID}-online-active-name`);localStorage.removeItem(tokenKey(room));try{ws?.close()}catch{};ws=null;screen('#title');setTimeout(loadRooms,250)}
$('#gameLeaveBtn').onclick=leaveCurrentRoom;$('#modalClose').onclick=closeModal;
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&currentRoomId&&(!ws||ws.readyState!==1))scheduleReconnect()});window.addEventListener('online',scheduleReconnect);
setInterval(()=>{if($('#title').classList.contains('active'))loadRooms()},5000);loadRooms();
const ar=localStorage.getItem(`${GAME_ID}-online-room`),an=localStorage.getItem(`${GAME_ID}-online-active-name`);if(ar&&an){currentRoomId=ar;currentPlayerName=an;connect()}
